In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df = "/content/drive/MyDrive/Mašinsko učenje/Dataset od drugog tima/WA_Fn-UseC_-Telco-Customer-Churn.csv "

In [3]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Mašinsko učenje/Dataset od drugog tima/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
import pandas as pd
num_instances = df.shape[0]
num_attributes = df.shape[1]

print("Broj instanci:", num_instances)
print("Broj atributa:", num_attributes)

Broj instanci: 7043
Broj atributa: 21

In [5]:
print(df.columns.tolist())

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Dodatak na kolonu gender:  
5% Female---> female  
Dodatak 5%: Male--> MALE

In [ ]:

import numpy as np

np.random.seed(42)
mask = (df["gender"] == "Female") & (np.random.rand(len(df)) < 0.05)
df.loc[mask, "gender"] = "female"

df["gender"].value_counts()

gender
Male      3555
Female    3319
female     169
Name: count, dtype: int64

In [ ]:
mask2 = (df["gender"] == "Male") & (np.random.rand(len(df)) < 0.05)
df.loc[mask2, "gender"] = "MALE"

df["gender"].value_counts()

gender
Male      3351
Female    3319
MALE       204
female     169
Name: count, dtype: int64

Dodatak na kolonu SeniorCitizen:  
6% 0--> nula  
7% 1---> jedan

In [ ]:
mask = (df["SeniorCitizen"] == 0) & (np.random.rand(len(df)) < 0.06)
df.loc[mask, "SeniorCitizen"] = "nula"

df["SeniorCitizen"].value_counts(dropna=False)

/tmp/ipython-input-881408615.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nula' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[mask, "SeniorCitizen"] = "nula"

SeniorCitizen
0       5559
1       1142
nula     342
Name: count, dtype: int64

In [ ]:
mask = (df["SeniorCitizen"] == 1) & (np.random.rand(len(df)) < 0.07)
df.loc[mask, "SeniorCitizen"] = "jedan"

df["SeniorCitizen"].value_counts(dropna=False)

SeniorCitizen
0        5559
1        1061
nula      342
jedan      81
Name: count, dtype: int64

Kolona Partner :  
4% No--> Noo  
4% Yes --> Yess  
3% No--> Yes

In [ ]:
mask_noo = (df["Partner"] == "No") & (np.random.rand(len(df)) < 0.04)
df.loc[mask_noo, "Partner"] = "Noo"

mask_yess = (df["Partner"] == "Yes") & (np.random.rand(len(df)) < 0.04)
df.loc[mask_yess, "Partner"] = "Yess"

df["Partner"].value_counts(dropna=False)

Partner
No      3502
Yes     3278
Noo      139
Yess     124
Name: count, dtype: int64

In [ ]:
mask = (df["Partner"] == "No") & (np.random.rand(len(df)) < 0.03)
df.loc[mask, "Partner"] = "Yes"

df["Partner"].value_counts(dropna=False)

Partner
No      3399
Yes     3381
Noo      139
Yess     124
Name: count, dtype: int64

Kolona Dependents:

6% No--> "No "  
3% Yes --> No

In [ ]:
mask_no_space = (df["Dependents"] == "No") & (np.random.rand(len(df)) < 0.06)
df.loc[mask_no_space, "Dependents"] = "No_"

In [ ]:
mask = (df["Dependents"] == "Yes") & (np.random.rand(len(df)) < 0.03)
df.loc[mask, "Dependents"] = "No"

df["Dependents"].value_counts(dropna=False)

Dependents
No     4698
Yes    2046
No_     299
Name: count, dtype: int64

Kolona tenure:  
3% instanci dobija šum od +-3%  
4% vrijdnosti koje imaju vrijednost = 12 stavljeno je kao 1

In [ ]:
mask_noise = np.random.rand(len(df)) < 0.03

df.loc[mask_noise, "tenure"] = df.loc[mask_noise, "tenure"] * (
    1 + np.random.uniform(-0.03, 0.03, mask_noise.sum())
)

df["tenure"] = df["tenure"].round().clip(lower=0)

df["tenure"].head(10)

/tmp/ipython-input-3425615071.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 9.73511101 71.07530858  1.02027457 22.95944428 43.29819449 70.24409242
 19.78804937 13.58936256 71.23674709  4.10960281 12.98618229 57.238742
 12.18750914  3.90758401 71.99656722 28.64809274 35.75842883 14.79254088
  4.89606366 71.40151313 48.78391685 67.36532112 42.49934159 49.45163492
  1.97560347  3.93056897 27.3461245  20.14880458 42.27271072 56.37664306
 32.99020342  3.92245951 66.90190575 15.91374464 67.77302359 13.00461477
 17.96243436 35.28126621 43.84585346 16.30657565  0.         66.8144982
 43.5430204  41.60892381 12.29528534 37.56661472  9.95562884 57.88074543
 50.57552939 68.2126906  70.67926474 62.12936838 11.64747242 68.94764653
 43.28830467 13.29083742 73.21315557 21.34004012 41.80450554 22.56752673
 19.54613443  0.98393156 17.62192424 42.47018331 11.02009921 30.30144095
 67.95925651 46.63770526 56.22987956 73.01189962  1.02411362 73.3795789
  6.01348872  2.05894075 56.09992367  7.01510831 14.69263938 70.48247272
 63.70793439 67.36912187 71.63354267 70.51386798 48.88267488 28.79309697
 53.60468719 23.16672384 12.91295957 40.80015455 37.48139795 49.87240197
  9.88000653  5.83539552  6.87555819 61.34882313 63.61802054  1.00989818
 48.35544918 40.27726618 28.24172783 71.77228536  0.99694639 54.26394097
 56.18760072  4.85637349 50.43507379 48.31255311 16.97590869 67.48803182
 60.0310494  45.45764527 63.80715268 11.30518632 61.86697673 28.68686445
 20.51201999 23.45422032 70.50789665  7.08519886  0.99338242  0.
 21.68573455  1.01416635 43.8909978   0.97961285  6.87094833 54.47002253
 14.80214994 72.13623808  8.12123802 16.28154275 10.80757679 20.59123314
  1.98364331  0.97886344 69.2610555  20.67565276 48.6881947  71.3742055
  7.0937771   4.91684345 26.49711553 15.55232393 22.92278348 33.26349156
 22.71194436 47.51801129  9.19820888  0.97536198 19.01431888  1.94225246
 70.06098646  7.82573133 46.34299901 52.20081406  9.8694389   0.98233782
 64.00082977  0.98350661  4.04748912 22.60166973 71.95779976 39.23490744
 39.74436838 31.9541238  17.78618632 72.92115274 49.16973087 58.99329515
  3.03655376  1.00882837 11.09875768 42.83311961 11.11490971 71.07669637
  1.02076396  0.98589046  7.07527472  3.03627365  2.04443843 15.44847687
 41.14157618 62.94108465 43.25976274 54.51411547 70.89453374 26.64557731
 70.94475798 56.55854838 12.64024316 64.42057     9.20239984 59.466725
  3.00313626 48.76574758  1.01274476 29.51201636 54.53137943 48.71382645
 12.83050162 12.03555536 72.10395811 11.20979678]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[mask_noise, "tenure"] = df.loc[mask_noise, "tenure"] * (

0     1.0
1    34.0
2     2.0
3    45.0
4     2.0
5     8.0
6    22.0
7    10.0
8    28.0
9    62.0
Name: tenure, dtype: float64

In [ ]:
mask_12 = df["tenure"] == 12

mask_change = (np.random.rand(mask_12.sum()) < 0.04)

df.loc[mask_12[mask_12].index[mask_change], "tenure"] = 1

df["tenure"].value_counts().head(10)

tenure
1.0     617
72.0    354
2.0     238
3.0     200
4.0     176
71.0    171
5.0     133
7.0     131
8.0     123
70.0    121
Name: count, dtype: int64

Kolona Phone Service  
7% podataka No---> NO  
10% Yes ---> YES  
4% Yes---> pretvaram u 1

In [ ]:
mask = (df["PhoneService"] == "No") & (np.random.rand(len(df)) < 0.07)
df.loc[mask, "PhoneService"] = "NO"

df["PhoneService"].value_counts(dropna=False)

PhoneService
Yes    6361
No      642
NO       40
Name: count, dtype: int64

In [ ]:
mask = (df["PhoneService"] == "Yes") & (np.random.rand(len(df)) < 0.1)
df.loc[mask, "PhoneService"] = "YES"

df["PhoneService"].value_counts(dropna=False)

PhoneService
Yes    5219
YES    1142
No      642
NO       40
Name: count, dtype: int64

In [ ]:
mask_yes = df["PhoneService"] == "Yes"

mask_change = (np.random.rand(mask_yes.sum()) < 0.04)

df.loc[mask_yes[mask_yes].index[mask_change], "PhoneService"] = 1

df["PhoneService"].value_counts(dropna=False)

PhoneService
Yes    5028
YES    1142
No      642
1       191
NO       40
Name: count, dtype: int64

Kolona MultipleLines  
8% No ----> no  
4% Yes----> No phone service


4% No Phone service ----> No fon servis  
5% podataka Yes ---> YEEES

In [ ]:
mask = (df["MultipleLines"] == "No") & (np.random.rand(len(df)) < 0.08)
df.loc[mask, "MultipleLines"] = "no"

df["MultipleLines"].value_counts(dropna=False)

MultipleLines
No                  3108
Yes                 2971
No phone service     682
no                   282
Name: count, dtype: int64

In [ ]:
mask = (df["MultipleLines"] == "Yes") & (np.random.rand(len(df)) < 0.04)
df.loc[mask, "MultipleLines"] = "No phone service"

df["MultipleLines"].value_counts(dropna=False)

MultipleLines
No                  3108
Yes                 2852
No phone service     801
no                   282
Name: count, dtype: int64

In [ ]:
mask = (df["MultipleLines"] == "No phone service") & (np.random.rand(len(df)) < 0.04)
df.loc[mask, "MultipleLines"] = "No fon servis"

df["MultipleLines"].value_counts(dropna=False)

MultipleLines
No                  3108
Yes                 2852
No phone service     760
no                   282
No fon servis         41
Name: count, dtype: int64

In [ ]:
mask = (df["MultipleLines"] == "Yes") & (np.random.rand(len(df)) < 0.05)
df.loc[mask, "MultipleLines"] = "YEEES"

df["MultipleLines"].value_counts(dropna=False)

MultipleLines
No                  3108
Yes                 2698
No phone service     760
no                   282
YEEES                154
No fon servis         41
Name: count, dtype: int64

Kolona InternetService  
10% DSL-----> DLS  
5% Fiber optic ----> Fibre optic

In [ ]:
mask = (df["InternetService"] == "DSL") & (np.random.rand(len(df)) < 0.10)
df.loc[mask, "InternetService"] = "DLS"

df["InternetService"].value_counts(dropna=False)

InternetService
Fiber optic    3096
DSL            2182
No             1526
DLS             239
Name: count, dtype: int64

In [ ]:
mask = (df["InternetService"] == "Fiber optic") & (np.random.rand(len(df)) < 0.05)
df.loc[mask, "InternetService"] = "Fibre optic"

df["InternetService"].value_counts(dropna=False)

InternetService
Fiber optic    2968
DSL            2182
No             1526
DLS             239
Fibre optic     128
Name: count, dtype: int64

Kolona Online Security
5% No internet service ----> No Intemet service
2% No ----> Yes
3% No----> NE
3% Yes ----> DA

In [ ]:
mask = (df["OnlineSecurity"] == "No internet service") & (np.random.rand(len(df)) < 0.05)
df.loc[mask, "OnlineSecurity"] = "No intemet service"

df["OnlineSecurity"].value_counts(dropna=False)

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1448
No intemet service       78
Name: count, dtype: int64

In [ ]:
mask = (df["OnlineSecurity"] == "No") & (np.random.rand(len(df)) < 0.02)
df.loc[mask, "OnlineSecurity"] = "Yes"


df["OnlineSecurity"].value_counts(dropna=False)

OnlineSecurity
No                     3426
Yes                    2091
No internet service    1448
No intemet service       78
Name: count, dtype: int64

In [ ]:
mask = (df["OnlineSecurity"] == "No") & (np.random.rand(len(df)) < 0.03)
df.loc[mask, "OnlineSecurity"] = "NE"

df["OnlineSecurity"].value_counts(dropna=False)

OnlineSecurity
No                     3333
Yes                    2091
No internet service    1448
NE                       93
No intemet service       78
Name: count, dtype: int64

In [ ]:
mask = (df["OnlineSecurity"] == "Yes") & (np.random.rand(len(df)) < 0.03)
df.loc[mask, "OnlineSecurity"] = "DA"

df["OnlineSecurity"].value_counts(dropna=False)

OnlineSecurity
No                     3333
Yes                    2035
No internet service    1448
NE                       93
No intemet service       78
DA                       56
Name: count, dtype: int64

Kolona OnlineBackup  
5% No internet service ----> No service  
8% Yes -----> YesYes  
5% No -----> NOU

In [ ]:
mask = (df["OnlineBackup"] == "No internet service") & (np.random.rand(len(df)) < 0.05)
df.loc[mask, "OnlineBackup"] = "No service"


df["OnlineBackup"].value_counts(dropna=False)

OnlineBackup
No                     3088
Yes                    2429
No internet service    1447
No service               79
Name: count, dtype: int64

In [ ]:

mask = (df["OnlineBackup"] == "Yes") & (np.random.rand(len(df)) < 0.08)
df.loc[mask, "OnlineBackup"] = "YesYes"

df["OnlineBackup"].value_counts(dropna=False)

OnlineBackup
No                     3088
Yes                    2230
No internet service    1447
YesYes                  199
No service               79
Name: count, dtype: int64

In [ ]:
mask = (df["OnlineBackup"] == "No") & (np.random.rand(len(df)) < 0.05)
df.loc[mask, "OnlineBackup"] = "NOU"

df["OnlineBackup"].value_counts(dropna=False)

OnlineBackup
No                     2929
Yes                    2230
No internet service    1447
YesYes                  199
NOU                     159
No service               79
Name: count, dtype: int64

Kolona DeviceProtection  
7% No internet service ----> NEMA INTERNETA  
8% No----> NE  
3% Yes----> null

In [ ]:
mask_no_internet = df['DeviceProtection'] == "No internet service"

n7 = int(len(df[mask_no_internet]) * 0.07)

idx_7 = df[mask_no_internet].sample(n7, random_state=42).index

df.loc[idx_7, 'DeviceProtection'] = "NEMA INTERNETA"

df['DeviceProtection'].value_counts()

DeviceProtection
No                     3095
Yes                    2422
No internet service    1420
NEMA INTERNETA          106
Name: count, dtype: int64

In [ ]:
mask_no2 = df['DeviceProtection'] == "No"

n8 = int(len(df[mask_no2]) * 0.08)

idx_8 = df[mask_no2].sample(n8, random_state=42).index

df.loc[idx_8, 'DeviceProtection'] = "NE"

In [ ]:
mask_yes2 = df['DeviceProtection'] == "Yes"

n3 = int(len(df[mask_yes2]) * 0.03)

idx_3 = df[mask_yes2].sample(n3, random_state=42).index

df.loc[idx_3, 'DeviceProtection'] = np.nan

Kolona TechSupport  
5% No internet service -----> No net  
5% Yes ----> No  
8% No----> _No_

In [ ]:
mask_ts_no_internet = df['TechSupport'] == "No internet service"

n5 = int(len(df[mask_ts_no_internet]) * 0.05)

idx_5 = df[mask_ts_no_internet].sample(n5, random_state=42).index

df.loc[idx_5, 'TechSupport'] = "No net"

In [ ]:
mask_ts_yes = df['TechSupport'] == "Yes"

n5_yes = int(len(df[mask_ts_yes]) * 0.05)

idx_5_yes = df[mask_ts_yes].sample(n5_yes, random_state=42).index

df.loc[idx_5_yes, 'TechSupport'] = "No"

In [ ]:
mask_ts_no = df['TechSupport'] == "No"

n8_no = int(len(df[mask_ts_no]) * 0.08)

idx_8_no = df[mask_ts_no].sample(n8_no, random_state=42).index

df.loc[idx_8_no, 'TechSupport'] = "_No_"

In [ ]:
df['TechSupport'].value_counts()

TechSupport
No                     3289
Yes                    1942
No internet service    1450
_No_                    286
No net                   76
Name: count, dtype: int64

Kolona StreamnigTv  
4% Yes----> null  
6% No ----> 0  
5% No internet service ----> No service internet

In [ ]:
import numpy as np

mask_st_yes = df['StreamingTV'] == "Yes"

n4_yes = int(len(df[mask_st_yes]) * 0.04)

idx_4_yes = df[mask_st_yes].sample(n4_yes, random_state=42).index

df.loc[idx_4_yes, 'StreamingTV'] = np.nan

In [ ]:
mask_st_no = df['StreamingTV'] == "No"

n6_no = int(len(df[mask_st_no]) * 0.06)

idx_6_no = df[mask_st_no].sample(n6_no, random_state=42).index

df.loc[idx_6_no, 'StreamingTV'] = "0"

In [ ]:
mask_st_no_int = df['StreamingTV'] == "No internet service"

n5_no_int = int(len(df[mask_st_no_int]) * 0.05)

idx_5_no_int = df[mask_st_no_int].sample(n5_no_int, random_state=42).index

df.loc[idx_5_no_int, 'StreamingTV'] = "No service internet"

In [ ]:
df['StreamingTV'].value_counts(dropna=False)

StreamingTV
No                     2642
Yes                    2599
No internet service    1450
0                       168
NaN                     108
No service internet      76
Name: count, dtype: int64

Kolona StreamningMovies  
6% Yes----> 1  
5% No----> No_No_No  
8% No internet service ----> NO INTERNET SERVICE

In [ ]:
mask_sm_yes = df['StreamingMovies'] == "Yes"

n6_yes = int(len(df[mask_sm_yes]) * 0.06)

idx_6_yes = df[mask_sm_yes].sample(n6_yes, random_state=42).index

df.loc[idx_6_yes, 'StreamingMovies'] = "1"

In [ ]:
mask_sm_no = df['StreamingMovies'] == "No"

n5_no = int(len(df[mask_sm_no]) * 0.05)

idx_5_no = df[mask_sm_no].sample(n5_no, random_state=42).index

df.loc[idx_5_no, 'StreamingMovies'] = "No_No_No"

In [ ]:
mask_sm_no_int = df['StreamingMovies'] == "No internet service"

n8_no_int = int(len(df[mask_sm_no_int]) * 0.08)

idx_8_no_int = df[mask_sm_no_int].sample(n8_no_int, random_state=42).index

df.loc[idx_8_no_int, 'StreamingMovies'] = "NO INTERNET SERVICE"

In [ ]:
df['StreamingMovies'].value_counts(dropna=False)

StreamingMovies
No                     2646
Yes                    2569
No internet service    1404
1                       163
No_No_No                139
NO INTERNET SERVICE     122
Name: count, dtype: int64

Kolona Contract  
10% Month-to-month---> M2M  
5% One year----> 1 year  
3% Two year ----> Three year  
4% Two year -----> TWO YEAR

In [ ]:
mask_ct_mtm = df['Contract'] == "Month-to-month"

n10_mtm = int(len(df[mask_ct_mtm]) * 0.10)

idx_10_mtm = df[mask_ct_mtm].sample(n10_mtm, random_state=42).index

df.loc[idx_10_mtm, 'Contract'] = "MTM"

In [ ]:
mask_ct_oneyear = df['Contract'] == "One year"

n5_oneyear = int(len(df[mask_ct_oneyear]) * 0.05)

idx_5_oneyear = df[mask_ct_oneyear].sample(n5_oneyear, random_state=42).index

df.loc[idx_5_oneyear, 'Contract'] = "1 year"

In [ ]:
mask_ct_twoyear = df['Contract'] == "Two year"

n5_twoyear = int(len(df[mask_ct_twoyear]) * 0.05)

idx_5_twoyear = df[mask_ct_twoyear].sample(n5_twoyear, random_state=42).index

df.loc[idx_5_twoyear, 'Contract'] = "Three year"

In [ ]:
mask_ct_twoyear2 = df['Contract'] == "Two year"

n4_twoyear = int(len(df[mask_ct_twoyear2]) * 0.04)

idx_4_twoyear = df[mask_ct_twoyear2].sample(n4_twoyear, random_state=42).index

df.loc[idx_4_twoyear, 'Contract'] = "TWO YEAR"

In [ ]:
df['Contract'].value_counts(dropna=False)

Contract
Month-to-month    3488
Two year          1547
One year          1400
MTM                387
Three year          84
1 year              73
TWO YEAR            64
Name: count, dtype: int64

Kolona PaperlessBilling  
7% No ----> No_NO_no  
5% Yes----> DA  
5% No -----> N0

In [ ]:
mask_pb_no = df['PaperlessBilling'] == "No"

n7_no = int(len(df[mask_pb_no]) * 0.07)

idx_7_no = df[mask_pb_no].sample(n7_no, random_state=42).index

df.loc[idx_7_no, 'PaperlessBilling'] = "NO_No_no"

In [ ]:
mask_pb_yes = df['PaperlessBilling'] == "Yes"

n5_yes = int(len(df[mask_pb_yes]) * 0.05)

idx_5_yes = df[mask_pb_yes].sample(n5_yes, random_state=42).index

df.loc[idx_5_yes, 'PaperlessBilling'] = "DA"

In [ ]:
mask_pb_no2 = df['PaperlessBilling'] == "No"

n5_no2 = int(len(df[mask_pb_no2]) * 0.05)

idx_5_no2 = df[mask_pb_no2].sample(n5_no2, random_state=42).index

df.loc[idx_5_no2, 'PaperlessBilling'] = "N0"

In [ ]:
df['PaperlessBilling'].value_counts(dropna=False)

PaperlessBilling
Yes         3963
No          2538
DA           208
NO_No_no     201
N0           133
Name: count, dtype: int64

Kolona PayementMethod  
8% Electronic check ----> E-check  
5% Credit card (automatic) ----> credit-card-auto  
5% Mailed check-----> Mail check  
8% Bank transfer (automatic) ----> Bank tranfser (automatic)

In [ ]:
mask_pm_ec = df['PaymentMethod'] == "Electronic check"

n8_ec = int(len(df[mask_pm_ec]) * 0.08)

idx_8_ec = df[mask_pm_ec].sample(n8_ec, random_state=42).index

df.loc[idx_8_ec, 'PaymentMethod'] = "E-check"

In [ ]:
mask_pm_cc = df['PaymentMethod'] == "Credit card (automatic)"

n5_cc = int(len(df[mask_pm_cc]) * 0.05)

idx_5_cc = df[mask_pm_cc].sample(n5_cc, random_state=42).index

df.loc[idx_5_cc, 'PaymentMethod'] = "credit-card-auto"

In [ ]:
mask_pm_mc = df['PaymentMethod'] == "Mailed check"

n5_mc = int(len(df[mask_pm_mc]) * 0.05)

idx_5_mc = df[mask_pm_mc].sample(n5_mc, random_state=42).index

df.loc[idx_5_mc, 'PaymentMethod'] = "Mail check"

In [ ]:
mask_pm_bt = df['PaymentMethod'] == "Bank transfer (automatic)"

n8_bt = int(len(df[mask_pm_bt]) * 0.08)

idx_8_bt = df[mask_pm_bt].sample(n8_bt, random_state=42).index

df.loc[idx_8_bt, 'PaymentMethod'] = "Bank tranfser (automatic)"

Kolona MonthlyCharges  
5% MonthlyCharges → ceil  
7% redova -----> pretvoreno u string  
8% redova ubačeno @ na početku

In [ ]:
import numpy as np
import math

n5_mc = int(len(df) * 0.05)
idx_5_mc = df.sample(n5_mc, random_state=42).index

df.loc[idx_5_mc, 'MonthlyCharges'] = df.loc[idx_5_mc, 'MonthlyCharges'].apply(np.ceil)

In [ ]:
n7_str = int(len(df) * 0.07)
idx_7_str = df.sample(n7_str, random_state=42).index

df.loc[idx_7_str, 'MonthlyCharges'] = df.loc[idx_7_str, 'MonthlyCharges'].astype(str)

/tmp/ipython-input-1970845941.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['25.0' '26.0' '20.0' '77.0' '51.0' '90.0' '78.0' '73.0' '104.0' '20.0'
 '21.0' '85.0' '51.0' '86.0' '21.0' '96.0' '54.0' '70.0' '89.0' '90.0'
 '71.0' '20.0' '80.0' '108.0' '105.0' '68.0' '90.0' '61.0' '92.0' '64.0'
 '104.0' '21.0' '86.0' '70.0' '95.0' '20.0' '22.0' '105.0' '105.0' '104.0'
 '70.0' '101.0' '76.0' '52.0' '95.0' '20.0' '77.0' '80.0' '90.0' '56.0'
 '20.0' '31.0' '114.0' '99.0' '97.0' '76.0' '102.0' '104.0' '25.0' '102.0'
 '71.0' '55.0' '21.0' '103.0' '71.0' '21.0' '20.0' '51.0' '20.0' '66.0'
 '75.0' '60.0' '99.0' '97.0' '100.0' '36.0' '91.0' '109.0' '20.0' '20.0'
 '75.0' '90.0' '55.0' '55.0' '21.0' '96.0' '105.0' '82.0' '25.0' '21.0'
 '36.0' '51.0' '90.0' '103.0' '21.0' '45.0' '91.0' '20.0' '96.0' '91.0'
 '71.0' '86.0' '21.0' '25.0' '21.0' '77.0' '69.0' '54.0' '92.0' '41.0'
 '85.0' '65.0' '20.0' '91.0' '21.0' '51.0' '94.0' '107.0' '45.0' '69.0'
 '79.0' '66.0' '20.0' '71.0' '45.0' '20.0' '79.0' '72.0' '20.0' '87.0'
 '95.0' '99.0' '105.0' '91.0' '21.0' '90.0' '86.0' '21.0' '50.0' '86.0'
 '96.0' '26.0' '99.0' '83.0' '21.0' '20.0' '60.0' '97.0' '59.0' '20.0'
 '21.0' '80.0' '76.0' '104.0' '96.0' '80.0' '108.0' '79.0' '107.0' '70.0'
 '71.0' '70.0' '76.0' '76.0' '36.0' '80.0' '46.0' '81.0' '102.0' '74.0'
 '59.0' '20.0' '26.0' '21.0' '41.0' '90.0' '70.0' '105.0' '76.0' '54.0'
 '80.0' '20.0' '79.0' '20.0' '21.0' '26.0' '26.0' '106.0' '86.0' '57.0'
 '20.0' '85.0' '110.0' '80.0' '100.0' '49.0' '106.0' '57.0' '96.0' '80.0'
 '71.0' '118.0' '85.0' '21.0' '20.0' '20.0' '85.0' '69.0' '84.0' '21.0'
 '26.0' '21.0' '70.0' '56.0' '93.0' '20.0' '65.0' '20.0' '95.0' '41.0'
 '108.0' '99.0' '21.0' '63.0' '20.0' '113.0' '21.0' '68.0' '75.0' '81.0'
 '61.0' '70.0' '74.0' '86.0' '91.0' '56.0' '76.0' '72.0' '85.0' '25.0'
 '78.0' '20.0' '36.0' '85.0' '111.0' '65.0' '65.0' '46.0' '20.0' '26.0'
 '75.0' '89.0' '77.0' '89.0' '90.0' '107.0' '60.0' '61.0' '26.0' '81.0'
 '96.0' '20.0' '45.0' '101.0' '62.0' '78.0' '44.0' '50.0' '97.0' '50.0'
 '20.0' '56.0' '80.0' '20.0' '25.0' '82.0' '46.0' '88.0' '59.0' '21.0'
 '85.0' '61.0' '66.0' '19.0' '81.0' '86.0' '70.0' '80.0' '77.0' '115.0'
 '53.0' '20.0' '95.0' '20.0' '116.0' '96.0' '21.0' '111.0' '96.0' '85.0'
 '100.0' '57.0' '110.0' '93.0' '79.0' '20.0' '20.0' '89.0' '60.0' '86.0'
 '46.0' '20.0' '21.0' '34.0' '20.0' '86.0' '21.0' '20.0' '96.0' '19.0'
 '96.0' '60.0' '100.0' '57.0' '92.0' '80.0' '46.0' '80.0' '70.0' '20.0'
 '102.0' '20.0' '34.0' '90.0' '62.0' '22.0' '98.0' '20.0' '81.0' '69.0'
 '67.0' '108.0' '21.0' '106.0' '91.0' '114.0' '35.0' '71.0' '74.0' '91.0'
 '85.0' '71.0' '19.65' '50.65' '24.65' '114.3' '106.55' '80.4' '92.5'
 '79.9' '55.3' '100.5' '33.45' '74.4' '52.5' '93.85' '90.6' '47.8' '20.4'
 '79.35' '54.25' '94.75' '70.1' '70.4' '78.95' '98.05' '72.1' '109.55'
 '94.2' '98.5' '69.05' '83.5' '25.6' '104.45' '23.05' '46.3' '79.6'
 '112.75' '83.75' '60.9' '51.05' '25.7' '60.65' '74.5' '78.65' '86.05'
 '88.45' '89.85' '19.95' '96.3' '24.75' '50.65' '20.1' '20.25' '80.8'
 '53.85' '20.0' '20.35' '80.0' '71.1' '20.0' '80.05' '69.55' '24.95'
 '85.7' '28.5' '88.8' '85.0' '88.55' '70.5' '109.15' '83.85' '24.75'
 '19.3' '54.55' '97.35' '20.75' '54.4' '74.4' '103.85' '107.65' '44.55'
 '111.95' '41.95' '84.8' '79.25' '95.65' '89.9' '88.35' '59.0' '91.25'
 '85.95' '70.0' '69.7' '34.4' '60.0' '80.9' '49.75' '111.3' '60.9' '20.25'
 '24.85' '105.35' '79.95' '90.05' '97.25' '84.05' '20.75' '89.55' '80.6'
 '19.4' '76.85' '111.3' '18.8' '44.8' '89.8' '94.25' '69.8' '24.9'
 '110.45' '90.45' '19.4' '50.0' '26.0' '55.95' '84.6' '29.75' '76.5'
 '115.75' '83.85' '74.4' '29.15' '98.8' '64.4' '79.65' '89.85' '59.8'
 '25.15' '116.25' '49.9' '49.85' '20.1' '56.3']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx_7_str, 'MonthlyCharges'] = df.loc[idx_7_str, 'MonthlyCharges'].astype(str)

In [ ]:
n8_at = int(len(df) * 0.08)
idx_8_at = df.sample(n8_at, random_state=42).index

df.loc[idx_8_at, 'MonthlyCharges'] = "@" + df.loc[idx_8_at, 'MonthlyCharges'].astype(str)

In [ ]:
df['MonthlyCharges'].value_counts(dropna=False)

MonthlyCharges
20.05    56
@20.0    43
19.95    41
19.7     41
19.85    41
         ..
72.0      1
43.05     1
@56.3     1
64.55     1
@64.4     1
Name: count, Length: 1810, dtype: int64

Kolona TotalCharges  
8% vrijednosti dodato na početku i na kraju _!_  
od 5% vrijednosti je oduzet broj 5  
3% vrijednosti obrisana . kod decimalnog broja  
Kod 3% vrijednosti je dodata 0 na početku

In [ ]:
n8_tc = int(len(df) * 0.08)
idx_8_tc = df.sample(n8_tc, random_state=42).index

df.loc[idx_8_tc, 'TotalCharges'] = df.loc[idx_8_tc, 'TotalCharges'].astype(str).apply(lambda x: f"_!_{x}_!_")

In [ ]:
import numpy as np

numeric_mask = df['TotalCharges'].apply(lambda x: isinstance(x, (int, float, np.integer, np.floating)))

n5_numeric = int(numeric_mask.sum() * 0.05)
idx_5_numeric = df[numeric_mask].sample(n5_numeric, random_state=42).index

df.loc[idx_5_numeric, 'TotalCharges'] = df.loc[idx_5_numeric, 'TotalCharges'] - 5

In [ ]:
import numpy as np

# jer neke si već pretvorila u string sa _!_ i sl.
numeric_mask_tc = df['TotalCharges'].apply(lambda x: isinstance(x, (int, float, np.integer, np.floating)))

n3_tc = int(numeric_mask_tc.sum() * 0.03)
idx_3_tc = df[numeric_mask_tc].sample(n3_tc, random_state=42).index

df.loc[idx_3_tc, 'TotalCharges'] = df.loc[idx_3_tc, 'TotalCharges'].astype(str).str.replace('.', '', regex=False)

In [ ]:
n5_tc_prefix = int(len(df) * 0.03)
idx_5_tc_prefix = df.sample(n5_tc_prefix, random_state=42).index

df.loc[idx_5_tc_prefix, 'TotalCharges'] = \
    df.loc[idx_5_tc_prefix, 'TotalCharges'].astype(str).apply(lambda x: "0" + x)

In [ ]:
df['TotalCharges'].value_counts(dropna=False)

TotalCharges
20.2             11
                 11
19.75             9
45.3              7
19.9              7
                 ..
168.9             1
_!_3306.85_!_     1
424.75            1
6565.85           1
1185              1
Name: count, Length: 6609, dtype: int64

In [ ]:
df['TotalCharges'][df['TotalCharges'].apply(lambda x: isinstance(x, str))].value_counts()

TotalCharges
20.2             11
                 11
19.75             9
45.3              7
19.9              7
                 ..
168.9             1
_!_3306.85_!_     1
424.75            1
6565.85           1
1185              1
Name: count, Length: 6609, dtype: int64

In [ ]:
df.to_csv("/content/dirty_telco.csv", index=False)